// File: App.xaml.cs
// Purpose: WPF application entry; auto-generated partial application class for the CyberAware UI.
// Notes: Kept intentionally minimal — startup behavior is controlled by App.xaml.
// File: App.xaml.cs
// Purpose: WPF application entry point partial class.
// Detailed notes:
// - This file contains the partial App class generated by WPF templates. The real startup
//   behavior (StartupUri, resources, themes) is defined in App.xaml. Keep this file minimal
//   and free of application logic; heavy startup operations belong in dedicated helpers.
// - This comment block is purely descriptive and does not alter runtime behavior.
// - If you need to change startup behavior (e.g., switch to a console entrypoint), modify
//   App.xaml or the project output type rather than this auto-generated file.
// Usage guidance:
// - Use App.xaml to configure application-level resources, themes and startup URIs.
// - Avoid adding blocking or long-running work here; prefer asynchronous initialization
//   helpers that can report progress to the UI.
using System.Windows;

namespace CyberAware
{
    public partial class App : Application
    {
    }
}
